C1 nav bar/home page
talent-path-pipeline/client pull request #35
Opened 2019-08-22 18:26 UTC by devmarantz

All my hard work

2019-08-23 16:30 UTC, samsaksfithian requested changes
Mostly good, but just with a couple minor things that should be tweaked

2019-08-23 16:30 UTC, samsaksfithian commented on .vscode/settings.json
> +{
Pls add `.vscode` to your `.gitignore`

2019-08-23 16:30 UTC, samsaksfithian commented on src/App.js
> +import './css/main.scss';
I think CSS imports should be below your other imports, but it doesn't matter that much.

2019-08-23 16:30 UTC, samsaksfithian commented on src/components/pages/HomePage.js
> +              <img src="https://img.icons8.com/ios-filled/50/000000/knowledge-sharing.png" />
We probably should store this image locally so it's bundled with the site and we don't need to externally fetch it

2019-08-23 16:30 UTC, samsaksfithian commented on src/css/main.scss
> +  background-color: white;
Gross, pure white

2019-08-23 16:30 UTC, samsaksfithian commented on src/css/navbar.scss
> +#nav-main {
Pls rename this file to `NavBar.scss`

2019-08-23 16:30 UTC, samsaksfithian commented on src/components/NavBar.js
> +  support: '/login',
```suggestion
  support: '/support',
  login: '/login',
```

2019-08-28 16:41 UTC, afterafx commented on src/components/pages/HomePage.js
> +              <img src="https://img.icons8.com/ios-filled/50/000000/knowledge-sharing.png" />
Okay I'll work on that later.

2019-08-29 14:29 UTC, closed without merging