27 lesson info
talent-path-pipeline/client pull request #36
Opened 2019-08-23 16:19 UTC by emily-yang

2019-08-26 17:17 UTC, samsaksfithian requested changes

2019-08-26 17:17 UTC, samsaksfithian commented on src/App.js
> +import HomePage from './components/pages/HomePage';
Use the destructure import, that's why we have an `index.js`
```suggestion
import { HomePage } from './components';
```

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/Lesson.js
> +    const {title, desc} = this.state
Idk why, but your Prettier seemingly isn't checking for end of line semicolons or bracket spacing and stuff? Maybe you saved while the VSCode extensions were down/loading?

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/index.js
> +// export { default as LessonPage } from './lesson/LessonInfo';
You should still import all of your new components here

```suggestion
export { default as LessonInfo } from './lesson/LessonInfo';
export { default as LessonVideo } from './lesson/LessonVideo';
export { default as LessonsPane } from './lesson/LessonsPane';
```

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/LessonInfo.js
> +const LessonInfo = ({ title, desc}) => <div className="lesson-info"><h4>Now playing:</h4><h2>{title || 'Lesson'}</h2><p>{desc || 'No description provided'}</p></div>
Similar to `Lesson`, this should be spaced/formatted.

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/Lesson.js
> +import LessonsPane from './LessonsPane';
Because of the `index.js`, as long as you import/export your components there (which you should), you can/should condense these into one line.
```suggestion
import { LessonVideo, LessonInfo, LessonsPane } from '..';
```

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/LessonLink.js
> +const LessonLink = ({title, src, length}) => <div className='lesson-link' key={title}>
Again, spacing/formatting is not great.

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/LessonLink.js
> +
This component has props, so you should have the `PropTypes`

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/LessonInfo.js
This component has props, so you should have the `PropTypes`

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/Lesson.js
> +
This component has props, so you should have the `PropTypes`

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/Lesson.js
> +    this.state = {
Does this component actually need a state? Do these things change? I feel like it makes more sense for them to just be Props that it splits up and passes down to the correct subcomponents.

You should put all your dummy data in App or a file and pass it into Lesson when you call it at the top, then the data should all get split up and distributed and passed down to where you need it.

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/LessonVideo.js
> +
This component has props, so you should have the `PropTypes`

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/LessonsPane.js
> +
This component has props, so you should have the `PropTypes`

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/LessonsPane.js
> +import LessonLink from './LessonLink';
Import using the `index.js` file for consistency

```suggestion
import { LessonLink } from '..';
```

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/LessonsPane.js
> +    this.state ={
Same as Lesson, I don't think this component needs a state. This info doesn't change until it reloads the component with the next video anyway, so this should just be passed in/down as props and displayed accordingly.

You should put all your dummy data in App or a file and pass it into Lesson when you call it at the top, then the data should all get split up and distributed and passed down to where you need it.

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/Lesson.js
> +        <LessonVideo />
Pass down the props:
```suggestion
        <LessonVideo link={this.props.link} />
```
(but with your actual props)

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/lesson/Lesson.js
> +        <LessonsPane />
Pass down the props:
```suggestion
        <LessonsPane lessons={this.props.lessons} />
```
(but with your actual props)

2019-08-26 17:17 UTC, samsaksfithian commented on src/components/pages/LessonPage.js
> +      <Lesson/>
This whole file is meaningless extra characters. There's no reason to have it be a component if it just returns another component. It's fine to just put all of the stuff from `Lesson` in here and not have that in the `./lessons` folder, and just have the subcomponents in there.

2019-08-26 17:17 UTC, samsaksfithian commented on src/css/lesson/colors.scss
> +:root {
Most of this is already in the `VARIABLES.scss` file, so you should use that and add any colors you added there instead of this new duplicate file.

2019-08-26 17:17 UTC, samsaksfithian commented on src/css/lesson/lesson-info.scss
> +.lesson-info {
Style files should be named the same as the component they are styling, so this should be `LessonInfo.scss`

2019-08-26 17:17 UTC, samsaksfithian commented on src/css/lesson/lesson-video.scss
> +iframe {
Style files should be named the same as the component they are styling, so this should be `LessonVideo.scss`

2019-08-26 17:17 UTC, samsaksfithian commented on src/css/lesson/lesson.scss
> +
Style files should be named the same as the component they are styling, so this should be `Lesson.scss`

2019-08-26 17:17 UTC, samsaksfithian commented on src/css/lesson/lesson.scss
> +@import './colors.scss';
```suggestion
@import './VARIABLES.scss';
```

2019-08-26 17:17 UTC, samsaksfithian commented on src/css/lesson/lessons-pane.scss
> +.lessons-pane {
Style files should be named the same as the component they are styling, so this should be `LessonsPane.scss`

2019-08-26 17:17 UTC, samsaksfithian commented on src/css/main.css
> +
```suggestion
@import '../css/VARIABLES.scss';
```

2019-09-03 15:36 UTC, samsaksfithian commented
Also resolves #21 and #23

2019-09-04 15:24 UTC, devmarantz approved these changes

2019-09-04 15:45 UTC, samsaksfithian approved these changes
Trusting @devmarantz 's review

2019-09-04 15:48 UTC, merged