3 authentication
talent-path-pipeline/client pull request #77
Opened 2019-10-17 18:33 UTC by Zyxel-1

Resolves #71 user Dashboard.

2019-10-17 23:49 UTC, afterafx commented
I get an error when trying to run this branch locally. 

Module not found: Can't resolve 'jwt-decode'

2019-10-29 18:28 UTC, emily-yang commented on src/App.js
> +            isSomething={this.state.isAuthenticated}
@devmarantz wtf is this `isSomething` attribute? Did you mean `isAuthenticated`?

2019-10-29 18:35 UTC, emily-yang commented on src/components/NavBar.js
> +
Mobile links for authentication should be moved to the bottom to stay consistent with the order for normal web app

2019-10-29 18:38 UTC, emily-yang commented on src/components/pages/DashboardPage.js
> +  // TODO: Implement Logout
Logout logic moved to nav bar

2019-10-29 18:45 UTC, emily-yang commented on src/components/registration/SignUp.js
> +      showSpisgdfgsdgsnner: false,
Who did this

2019-10-29 18:49 UTC, emily-yang requested changes
Please see comments in the PR

2019-10-31 17:17 UTC, devmarantz commented on src/App.js
> +            isSomething={this.state.isAuthenticated}
Yeah I did!  Changed it, thank you for catching this.

2019-11-01 18:00 UTC, emily-yang approved these changes

2019-11-01 18:00 UTC, emily-yang commented on src/components/pages/DashboardPage.js
> +!
Suggestion: use a template string
```
{`Welcome, ${this.state.userName || 'Anon'}`}

```

2019-11-01 18:00 UTC, emily-yang commented on src/components/pages/DashboardPage.js
> +              {this.state.userID}
Suggestion: use a template string

2019-11-01 18:25 UTC, emily-yang commented on src/components/registration/SignUp.js
> +            <a href="www.google.com">Terms and Agreement</a>
This link goes to `http://localhost:3000/www.google.com`

2019-11-01 19:32 UTC, emily-yang requested changes

2019-11-01 19:32 UTC, emily-yang commented on src/components/NavBar.js
> +    this.state.isAuthenticated = isAuthenticated;
Never mutate state directly. Alternative: 
```
  componentDidUpdate(prevProps, prevState) {
    const { isAuthenticated } = this.props;
    if (isAuthenticated !== prevState.isAuthenticated) {
      this.setState({ isAuthenticated });
    }
  }
```

2019-11-01 19:54 UTC, Zyxel-1 commented on src/components/NavBar.js
> +    this.state.isAuthenticated = isAuthenticated;
@devmarantz You did this section

2019-11-01 20:25 UTC, emily-yang requested changes

2019-11-01 20:25 UTC, emily-yang commented on src/components/registration/SignUp.js
> +            <a href="https://www.termsandcondiitionssample.com/live.php?token=bYAxBa2kby8ugr9x4eWMbKKgXnxOQyNg" target="_blank">Terms and Agreement</a>
Add `rel="noopener noreferrer"` to the tag to prevent security vulnerability

2019-11-05 17:48 UTC, devmarantz approved these changes
Resolved requested changes

2019-11-05 20:26 UTC, emily-yang approved these changes

2019-11-06 18:04 UTC, merged